"""empty message

Revision ID: 53e1dceb842f
Revises: 
Create Date: 2017-12-16 16:22:20.456579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e1dceb842f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=70), nullable=True),
    sa.Column('first_name', sa.String(length=70), nullable=True),
    sa.Column('last_name', sa.String(length=70), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('logo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text(u'now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('customer_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], [u'customers.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('current_balance', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_transaction_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], [u'customers.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('wallet_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.String(length=100), nullable=False),
    sa.Column('transaction_amount', sa.Integer(), nullable=False),
    sa.Column('remaining_amount', sa.Integer(), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cancellation_date', sa.DateTime(), nullable=True),
    sa.Column('cancelled_transaction_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_transaction_id'], [u'transactions.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], [u'customer_wallets.id'], ondelete=u'CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('customer_wallets')
    op.drop_table('customer_tokens')
    op.drop_table('customers')
    # ### end Alembic commands ###
